version: "3.0"
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysqldb:/var/lib/mysql    # created volume named via line[27] attached to mysql container data
  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:7.12.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  pharmacy-on-tap:
    build: .
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ELASTIC_HOST=${ELASTIC_HOST}
    ports:
      - 5000:5000
    depends_on:
      - mysql
      - elasticsearch
volumes:
  mysqldb:      # It will create a volume named mysqldb